// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://roihkvsxbpfuosqfpoxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvaWhrdnN4YnBmdW9zcWZwb3hqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0ODIyNjIsImV4cCI6MjA2MTA1ODI2Mn0.tm-QQnnWM_9e64sD3hLXMynALKmC9swIDb6NGjVAkT0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);